<?php require_once __DIR__ . '/../includes/page.php';
$u = page_guard(['restaurant_owner','restaurant_staff']);
if (!has_permission($u,'manage_inventory')) { http_response_code(403); page_head('Inventory access'); nav_bar($u); echo '<main class="wrap"><div class="empty"><b>You do not have access to inventory.</b>Ask your restaurant owner or manager to assign inventory permissions.</div></main>'; page_foot(); exit; }
page_head('Inventory'); nav_bar($u); ?>
<main class="wrap inventory-page">
  <header class="inventory-heading"><div><div class="eyebrow">RESTAURANT OPERATIONS</div><h1>Inventory</h1><p>Track ingredients, receive purchases and keep an eye on low stock.</p></div><div class="inventory-actions"><button class="btn sm ghost" type="button" data-open-dialog="supplierDialog">Add supplier</button><button class="btn sm" type="button" data-open-dialog="ingredientDialog">+ Add ingredient</button></div></header>
  <section class="inventory-metrics" aria-label="Inventory summary"><article><span class="inventory-metric-icon">◩</span><span><small>INGREDIENTS</small><b id="metricIngredients">—</b></span></article><article><span class="inventory-metric-icon warning">!</span><span><small>LOW STOCK</small><b id="metricLow">—</b></span></article><article><span class="inventory-metric-icon sage">KSh</span><span><small>ESTIMATED STOCK VALUE</small><b id="metricValue">—</b></span></article></section>
  <section class="dash-panel inventory-table-panel"><div class="panel-heading"><div><h2>Ingredient usage report</h2><p>Purchases, recipe use, waste and stock adjustments for your selected dates.</p></div></div><form id="inventoryReportFilter" class="inventory-report-filter"><label>From<input type="date" id="reportFrom" required></label><label>To<input type="date" id="reportTo" required></label><button class="btn sm" type="submit">Update report</button><span id="reportEstimateNote">Usage cost is estimated using current ingredient costs.</span></form><div id="inventoryReport" class="inventory-report-table"><div class="inventory-loading">Loading usage report…</div></div></section>
  <section class="dash-panel inventory-table-panel"><div class="panel-heading"><div><h2>Ingredients</h2><p>Current quantity, minimum level and estimated cost</p></div><button class="btn sm ghost" id="inventoryRefresh" type="button">Refresh</button></div><div id="inventoryIngredients" class="inventory-table-wrap" aria-live="polite"><div class="inventory-loading">Loading your inventory…</div></div></section>
  <div class="inventory-lower"><section class="dash-panel"><div class="panel-heading"><div><h2>Recent stock activity</h2><p>Purchases, adjustments and waste</p></div></div><div id="inventoryMovements" class="inventory-activity-list"><div class="inventory-loading">Loading activity…</div></div></section>
    <section class="dash-panel"><div class="panel-heading"><div><h2>Suppliers</h2><p>Your active ingredient suppliers</p></div><button class="btn sm ghost" type="button" data-open-dialog="supplierDialog">+ Add</button></div><div id="inventorySuppliers" class="inventory-supplier-list"><div class="inventory-loading">Loading suppliers…</div></div></section></div>
  <section class="dash-panel inventory-table-panel"><div class="panel-heading"><div><h2>Purchase history</h2><p>Recently received ingredient purchases</p></div></div><div id="inventoryPurchases" class="inventory-purchases-list"><div class="inventory-loading">Loading purchases…</div></div></section>
  <section class="dash-panel inventory-table-panel recipes-panel"><div class="panel-heading"><div><h2>Menu item recipes</h2><p>Set ingredient quantities used to prepare one menu item. Stock is deducted when an order is placed.</p></div><button class="btn sm" type="button" data-open-dialog="recipeDialog">+ Add recipe</button></div><div id="inventoryRecipes" class="inventory-recipe-list"><div class="inventory-loading">Loading recipes…</div></div></section>
</main>

<dialog class="inventory-dialog" id="ingredientDialog"><form id="ingredientForm" novalidate><div class="inventory-dialog-head"><div><h2 id="ingredientTitle">Add ingredient</h2><p>Set the stock unit, minimum level and current cost.</p></div><button type="button" class="dialog-close" data-close-dialog aria-label="Close">×</button></div><input type="hidden" name="id"><div class="inventory-form-grid"><div class="setting-field"><label for="ingredientName">Ingredient name</label><input id="ingredientName" name="name" required maxlength="150" placeholder="e.g. Beef mince"><div class="err" data-err="name"></div></div><div class="setting-field"><label for="ingredientUnit">Unit</label><select id="ingredientUnit" name="unit" required><option value="g">Grams (g)</option><option value="kg">Kilograms (kg)</option><option value="ml">Millilitres (ml)</option><option value="l">Litres (l)</option><option value="pcs">Pieces (pcs)</option><option value="portion">Portions</option><option value="bottle">Bottles</option><option value="pack">Packs</option><option value="each">Each</option><option value="unit">Units</option></select><div class="err" data-err="unit"></div></div><div class="setting-field ingredient-opening"><label for="initialStock">Opening stock</label><input id="initialStock" name="initial_stock" type="number" min="0" step="0.001" value="0"><small class="field-hint">Recorded as an opening stock movement.</small><div class="err" data-err="initial_stock"></div></div><div class="setting-field"><label for="minStock">Low-stock threshold</label><input id="minStock" name="min_stock" type="number" min="0" step="0.001" value="0" required><div class="err" data-err="min_stock"></div></div><div class="setting-field"><label for="ingredientCost">Cost per unit (KSh)</label><input id="ingredientCost" name="cost_per_unit" type="number" min="0" step="0.01" value="0" required><div class="err" data-err="cost_per_unit"></div></div></div><div class="inventory-dialog-actions"><div class="msg" data-form-message></div><button class="btn" type="submit">Save ingredient</button></div></form></dialog>

<dialog class="inventory-dialog" id="movementDialog"><form id="movementForm" novalidate><div class="inventory-dialog-head"><div><h2 id="movementTitle">Adjust stock</h2><p id="movementHelp">Enter a positive or negative change in stock.</p></div><button type="button" class="dialog-close" data-close-dialog aria-label="Close">×</button></div><input type="hidden" name="ingredient_id"><input type="hidden" name="action"><div class="inventory-form-grid"><div class="setting-field"><label for="movementQuantity">Quantity</label><input id="movementQuantity" name="quantity" type="number" step="0.001" required><div class="err" data-err="quantity"></div></div><div class="setting-field"><label for="movementNotes">Reason or note</label><input id="movementNotes" name="notes" maxlength="255" placeholder="Optional note"></div></div><div class="inventory-dialog-actions"><div class="msg" data-form-message></div><button class="btn" type="submit" id="movementSubmit">Save movement</button></div></form></dialog>

<dialog class="inventory-dialog" id="supplierDialog"><form id="supplierForm" novalidate><div class="inventory-dialog-head"><div><h2>Add supplier</h2><p>Save a supplier for your purchase records.</p></div><button type="button" class="dialog-close" data-close-dialog aria-label="Close">×</button></div><div class="inventory-form-grid"><div class="setting-field"><label for="supplierName">Supplier name</label><input id="supplierName" name="name" required maxlength="150"><div class="err" data-err="name"></div></div><div class="setting-field"><label for="supplierPhone">Phone</label><input id="supplierPhone" name="phone" type="tel" maxlength="30"><div class="err" data-err="phone"></div></div><div class="setting-field inventory-wide"><label for="supplierEmail">Email</label><input id="supplierEmail" name="email" type="email" maxlength="150"><div class="err" data-err="email"></div></div></div><div class="inventory-dialog-actions"><div class="msg" data-form-message></div><button class="btn" type="submit">Save supplier</button></div></form></dialog>

<dialog class="inventory-dialog purchase-dialog" id="purchaseDialog"><form id="purchaseForm" novalidate><div class="inventory-dialog-head"><div><h2>Receive stock</h2><p>Record a supplier purchase and add the quantities to inventory.</p></div><button type="button" class="dialog-close" data-close-dialog aria-label="Close">×</button></div><div class="inventory-form-grid"><div class="setting-field"><label for="purchaseSupplier">Supplier</label><select id="purchaseSupplier" name="supplier_id"><option value="0">No supplier selected</option></select></div><div class="setting-field"><label for="purchaseDate">Purchase date</label><input id="purchaseDate" name="purchased_at" type="date" required></div><div class="setting-field inventory-wide"><label for="purchaseNotes">Notes</label><input id="purchaseNotes" name="notes" maxlength="2000" placeholder="Invoice number or delivery note"></div></div><div class="purchase-items-heading"><b>Purchase items</b><button type="button" class="link" id="addPurchaseItem">+ Add item</button></div><div id="purchaseItemRows"></div><div class="inventory-dialog-actions"><div class="msg" data-form-message></div><button class="btn" type="submit">Receive purchase</button></div></form></dialog>
<dialog class="inventory-dialog recipe-dialog" id="recipeDialog"><form id="recipeForm" novalidate><div class="inventory-dialog-head"><div><h2 id="recipeTitle">Add menu recipe</h2><p>Enter the quantity of each ingredient for one menu item.</p></div><button type="button" class="dialog-close" data-close-dialog aria-label="Close">×</button></div><div class="setting-field"><label for="recipeProduct">Menu item</label><select id="recipeProduct" name="product_id" required><option value="">Choose a menu item</option></select></div><div class="purchase-items-heading"><b>Ingredients per item</b><button type="button" class="link" id="addRecipeIngredient">+ Add ingredient</button></div><div id="recipeIngredientRows"></div><div class="inventory-dialog-actions"><div class="msg" data-form-message></div><button class="btn" type="submit">Save recipe</button></div></form></dialog>
<?php page_foot('inventory.js');
