<?php require_once __DIR__ . '/../includes/page.php';
$u=page_guard(['customer']);$pdo=db();$id=(int)$u['id'];
$q=$pdo->prepare("SELECT r.id,r.name,ls.shillings_per_point,ls.points_per_earn,ls.redemption_points,ls.redemption_value,COALESCE(la.points_balance,0) AS balance
 FROM loyalty_settings ls JOIN restaurants r ON r.id=ls.restaurant_id LEFT JOIN loyalty_accounts la ON la.restaurant_id=r.id AND la.user_id=?
 WHERE ls.is_enabled=1 AND r.status='active' AND r.deleted_at IS NULL ORDER BY r.name");$q->execute([$id]);$programs=$q->fetchAll();
$h=$pdo->prepare('SELECT lt.points,lt.type,lt.description AS notes,lt.created_at,r.name AS restaurant_name FROM loyalty_transactions lt JOIN restaurants r ON r.id=lt.restaurant_id WHERE lt.customer_user_id=? ORDER BY lt.created_at DESC LIMIT 50');$h->execute([$id]);$history=$h->fetchAll();
page_head('My rewards');nav_bar($u); ?>
<main class="customer-home customer-workspace customer-list-page"><header class="customer-heading"><div><div class="eyebrow">YOUR ACCOUNT</div><h1>My rewards</h1><p>Track points earned at participating restaurants.</p></div><a class="customer-browse" href="<?= e(url()) ?>">Browse restaurants <span>→</span></a></header>
<section class="dash-panel customer-panel"><div class="panel-heading"><div><h2>Available programs</h2><p>Earn points when you sign in and complete a paid order.</p></div></div><?php if($programs): ?><div class="loyalty-customer-list"><?php foreach($programs as $program): ?><article class="loyalty-customer-card"><span class="loyalty-points-mark">★</span><span class="loyalty-customer-main"><b><?= e($program['name']) ?></b><small><?= number_format((int)$program['points_per_earn']) ?> point<?= (int)$program['points_per_earn']===1?'':'s' ?> for every KSh <?= number_format((int)$program['shillings_per_point']) ?> spent</small><small>Reward terms: <?= number_format((int)$program['redemption_points']) ?> points = KSh <?= number_format((float)$program['redemption_value'],2) ?></small></span><strong><?= number_format((int)$program['balance']) ?> pts</strong></article><?php endforeach ?></div><?php else: ?><div class="dash-empty"><span>★</span><b>No rewards programs available yet</b><p>When a restaurant turns on rewards, it will appear here.</p></div><?php endif ?></section>
<section class="dash-panel customer-panel loyalty-history"><div class="panel-heading"><div><h2>Points activity</h2><p>Your latest loyalty points activity.</p></div></div><?php if($history): ?><div class="loyalty-customer-list"><?php foreach($history as $item): ?><article class="loyalty-customer-card"><span class="loyalty-points-mark">★</span><span class="loyalty-customer-main"><b><?= e($item['restaurant_name']) ?></b><small><?= e($item['notes']?:ucfirst($item['type'])) ?> · <?= e(date('M j, Y',strtotime($item['created_at']))) ?></small></span><strong class="<?= (int)$item['points']<0?'loyalty-negative':'' ?>"><?= (int)$item['points']>0?'+':'' ?><?= number_format((int)$item['points']) ?> pts</strong></article><?php endforeach ?></div><?php else: ?><div class="dash-empty"><b>No points activity yet</b><p>Complete an eligible order at a participating restaurant to earn points.</p></div><?php endif ?></section></main>
<?php page_foot();
